# Generated by Django 4.1.1 on 2023-01-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hududlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('vaqt_farqi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('ochish', models.TimeField()),
                ('yopish', models.TimeField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hududlar.hududlar')),
            ],
        ),
    ]
