# Generated by Django 4.1.5 on 2023-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hududlar', '0002_alter_vaqt_hudud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaqt',
            name='ochish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vaqt',
            name='yopish',
            field=models.DateTimeField(),
        ),
    ]
