# Generated by Django 4.1.5 on 2023-02-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hududlar', '0003_alter_vaqt_ochish_alter_vaqt_yopish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaqt',
            name='ochish',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vaqt',
            name='yopish',
            field=models.TimeField(),
        ),
    ]
