# Generated by Django 4.1.5 on 2023-02-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hududlar', '0009_alter_videocategory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('vaqt_farqi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NamozVaqti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('bomdod', models.TimeField()),
                ('peshin', models.TimeField()),
                ('asr', models.TimeField()),
                ('shom', models.TimeField()),
                ('xufton', models.TimeField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hududlar.hududlar')),
            ],
        ),
    ]
