# Generated by Django 4.1.5 on 2023-02-25 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hududlar', '0010_viloyat_namozvaqti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namozvaqti',
            name='hudud',
        ),
        migrations.AddField(
            model_name='namozvaqti',
            name='viloyat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hududlar.viloyat'),
            preserve_default=False,
        ),
    ]
